import React, { useEffect, useMemo, useState } from 'react';
import snapshot from '../data/calendar.json';

interface CalendarEntry { week: number; day: string; date: string; cedTopic: string; learningTarget: string; classwork: string; campbell: string; biozone: string; homework: string; apTarget: string; }
const CSV_URL = import.meta.env.VITE_NAVIGATOR_CSV_URL as string | undefined;
const fields: Array<[keyof CalendarEntry, string]> = [['learningTarget','Learning target'],['classwork','In class'],['homework','After class'],['campbell','Campbell'],['biozone','BIOZONE'],['apTarget','AP target']];

function parseCsv(text: string): CalendarEntry[] {
  const rows: string[][]=[]; let row:string[]=[]; let cell=''; let quoted=false;
  for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&quoted&&n==='"'){cell+='"';i++;}else if(c==='"')quoted=!quoted;else if(c===','&&!quoted){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&n==='\n')i++;row.push(cell);if(row.some(Boolean))rows.push(row);row=[];cell='';}else cell+=c;}
  if(cell||row.length){row.push(cell);rows.push(row);} const header=rows.findIndex(r=>r.some(v=>v.trim().toLowerCase()==='week')); if(header<0)return [];
  const isoDate=(value:string)=>{const d=new Date(value);return Number.isNaN(d.getTime())?value:d.toISOString().slice(0,10);};
  return rows.slice(header+1).map(r=>({week:Number(r[0])||0,day:r[1]||'',date:isoDate(r[2]||''),cedTopic:r[3]||'',learningTarget:r[4]||'',classwork:r[5]||'',campbell:r[6]||'',biozone:r[7]||'',homework:r[8]||'',apTarget:r[9]||''})).filter(e=>e.date&&Object.values(e).some(Boolean));
}
const formatDate=(value:string)=>new Intl.DateTimeFormat('en-US',{weekday:'long',month:'long',day:'numeric'}).format(new Date(`${value}T12:00:00`));

const Navigator: React.FC = () => {
  const [entries,setEntries]=useState<CalendarEntry[]>(snapshot as CalendarEntry[]); const [search,setSearch]=useState(''); const [topic,setTopic]=useState('all'); const [showPast,setShowPast]=useState(true); const [live,setLive]=useState(false);
  useEffect(()=>{if(!CSV_URL)return;fetch(CSV_URL).then(r=>{if(!r.ok)throw new Error();return r.text();}).then(t=>{const p=parseCsv(t);if(p.length){setEntries(p);setLive(true);}}).catch(()=>setLive(false));},[]);
  const today=new Date();today.setHours(0,0,0,0);const todayIso=today.toISOString().slice(0,10);
  const topics=useMemo(()=>[...new Set(entries.map(e=>e.cedTopic).filter(Boolean))].sort((a,b)=>a.localeCompare(b,undefined,{numeric:true})),[entries]);
  const visible=useMemo(()=>entries.filter(e=>(showPast||e.date>=todayIso)&&(topic==='all'||e.cedTopic===topic)&&(!search||Object.values(e).join(' ').toLowerCase().includes(search.toLowerCase()))).sort((a,b)=>b.date.localeCompare(a.date)),[entries,search,topic,showPast,todayIso]);
  return <main className="mx-auto max-w-7xl px-4 py-8">
    <section className="mb-7 rounded-3xl bg-gradient-to-br from-cyan-800 to-teal-600 p-6 text-white shadow-xl sm:p-8"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="mb-2 text-sm font-bold uppercase tracking-[0.18em] text-cyan-100">2025 CED aligned</p><h2 className="text-3xl font-black sm:text-4xl">Daily Learning Navigator</h2><p className="mt-2 max-w-2xl text-cyan-50">Classwork, readings, BIOZONE pages, homework, and AP learning targets—organized for quick daily use.</p></div><span className="w-fit rounded-full bg-white/15 px-3 py-1 text-xs font-semibold">{live?'Live Google Sheet':'Saved schedule'}</span></div></section>
    <section className="mb-6 grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm md:grid-cols-[1fr_180px_auto]"><label className="text-sm font-semibold text-slate-700">Search<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Lab, reading, topic…" className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 font-normal outline-none focus:border-cyan-600 focus:ring-2 focus:ring-cyan-100" /></label><label className="text-sm font-semibold text-slate-700">CED topic<select value={topic} onChange={e=>setTopic(e.target.value)} className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 font-normal"><option value="all">All topics</option>{topics.map(t=><option key={t}>{t}</option>)}</select></label><label className="flex items-center gap-2 self-end rounded-lg bg-slate-100 px-3 py-2 text-sm font-semibold"><input type="checkbox" checked={showPast} onChange={e=>setShowPast(e.target.checked)} className="accent-cyan-700" />Show past days</label></section>
    <div className="mb-3 flex items-center justify-between"><p className="text-sm text-slate-500">Newest dates appear first</p><p className="text-sm font-semibold text-slate-700">{visible.length} school days</p></div>
    <section className="space-y-4">{visible.map((entry,index)=>{const isToday=entry.date===todayIso;return <article key={`${entry.date}-${index}`} className={`overflow-hidden rounded-2xl border bg-white shadow-sm ${isToday?'border-cyan-500 ring-4 ring-cyan-100':'border-slate-200'}`}><header className={`flex flex-col gap-2 border-b px-5 py-4 sm:flex-row sm:items-center sm:justify-between ${isToday?'bg-cyan-50':'bg-slate-50'}`}><div className="flex items-center gap-3"><div className="rounded-xl bg-slate-900 px-3 py-2 text-center text-white"><div className="text-[10px] font-bold uppercase tracking-wider">Week</div><div className="text-xl font-black leading-none">{entry.week}</div></div><div><h3 className="text-lg font-extrabold text-slate-950">{formatDate(entry.date)}</h3><p className="text-sm text-slate-500">{entry.day}</p></div></div><div className="flex items-center gap-2">{isToday&&<span className="rounded-full bg-cyan-700 px-3 py-1 text-xs font-bold text-white">Today</span>}{entry.cedTopic&&<span className="rounded-full bg-teal-100 px-3 py-1 text-xs font-bold text-teal-800">CED {entry.cedTopic}</span>}</div></header><div className="grid gap-3 p-5 md:grid-cols-2">{fields.map(([key,label])=>entry[key]?<div key={key} className={`${key==='learningTarget'||key==='classwork'||key==='homework'?'md:col-span-2':''} rounded-xl border border-slate-200 p-4`}><h4 className="mb-1 text-xs font-extrabold uppercase tracking-wider text-cyan-700">{label}</h4><p className="whitespace-pre-line text-sm leading-6 text-slate-700">{entry[key]}</p></div>:null)}</div></article>})}{!visible.length&&<div className="rounded-2xl border border-dashed border-slate-300 bg-white p-12 text-center text-slate-500">No calendar entries match those filters.</div>}</section>
  </main>;
};
export default Navigator;
